src/CourseWork.Web/Controllers/FilesController.cs
namespace CourseWork.Web.Controllers
{
    using CourseWork.Models;
    using CourseWork.Web.Attributes;
    using CourseWork.Web.Interfaces;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;

    /// <summary>
    /// Контроллер для работы с отправкой и загрузкой файлов.
    /// </summary>
    [ExceptionFilter]
    public class FilesController : Controller
    {
        /// <summary>
        /// Сервис для сериализации и десериализации.
        /// </summary>
        private readonly ISerializer _serializer;

        /// <summary>
        /// HttpClient.
        /// </summary>
        private readonly IDistributionHttpClient _httpClient;

        /// <summary>
        /// Путь к папке с файлами.
        /// </summary>
        private readonly string _pathToFiles;

        /// <summary>
        /// Инициализирует новый объект класса <see cref="FilesController"/>.
        /// </summary>
        /// <param name="httpClient">HttpClient.</param>
        /// <param name="environment">IWebHostEnvironment.</param>
        /// <param name="serializer">Сервис для сериализации и десериализации.</param>
        public FilesController(IDistributionHttpClient httpClient, IWebHostEnvironment environment, ISerializer serializer)
        {
            _httpClient = httpClient;
            _pathToFiles = Path.Combine(environment.WebRootPath, "files");
            _serializer = serializer;
        }

        /// <summary>
        /// Отправляет данные матрицы и вектора на сервер и получает результат решения СЛАУ.
        /// </summary>
        /// <param name="matrixFileName">Имя файла с матрицей.</param>
        /// <param name="vectorFileName">Имя файла с вектором.</param>
        /// <returns>Файл с результатом.</returns>
        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> SendMatrixAndVectorToServer(string number)
        {
            var matrix = await _serializer.DeserializeMatrix(Path.Combine(_pathToFiles, $"A{number}" + ".txt"));
            var vector = await _serializer.DeserializeVector(Path.Combine(_pathToFiles, $"B{number}" + ".txt"));
            var data = new DataModel
            {
                Matrix = matrix,
                Vector = vector,
            };
            var s = new Stopwatch();
            s.Restart();
            var result = await _httpClient.SendFileToServer(data);
            s.Stop();
            Console.WriteLine($"Общее время решения: {s.ElapsedMilliseconds}");
            return File(_serializer.SerializeVector(result.Vector), "text/plain", $"X{number}.txt");
        }
    }
}

src/CourseWork.Web/Controllers/HomeController.cs
namespace CourseWork.Web.Controllers
{
    using CourseWork.Web.Attributes;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Контроллер главной страницы.
    /// </summary>
    [ExceptionFilter]
    public class HomeController : Controller
    {
        /// <summary>
        /// Начальная страница.
        /// </summary>
        /// <returns>Представление с главной страницей.</returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/CourseWork.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}
<header class="header">
    <p>
        СЕТЕВОЕ ПРИЛОЖЕНИЕ ДЛЯ РАСПРЕДЕЛЁННОГО РЕШЕНИЯ СЛАУ С ИСПОЛЬЗОВАНИЕМ ПРОТОКОЛА HTTP
    </p>
    
</header>
<hr>
<div class="content">
    <div class="text-center">
        <form asp-controller="Files" asp-action="SendMatrixAndVectorToServer" method="post" enctype="multipart/form-data">
            <select name="number">
                <option value="0">СЛАУ 0</option>
                <option value="1">СЛАУ 1</option>
                <option value="2">СЛАУ 2</option>
                <option value="3">СЛАУ 3</option>
                
            </select>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="submit" value="Отправить данные" id="btn" />
        </form>
    </div>
</div>

src/CourseWork.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWork.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWork.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>